sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0

mysql:
  database: drupal
  username: root
  encoding: utf8

addons:
  apt:
    packages:
    - nginx

cache:
  directories:
  - $HOME/www
  - $HOME/.drush

install:
  # Install web server.
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - nginx -c $TRAVIS_BUILD_DIR/.travis/nginx.conf
  # Install Drush and Drupal.
  - wget -P ~/ https://github.com/drush-ops/drush/releases/download/8.0.0-rc3/drush.phar
  - test ! -f ~/www/index.php && git clone --depth 1 --branch 8.0.x http://git.drupal.org/project/drupal.git ~/www || true
  - ln -s $TRAVIS_BUILD_DIR ~/www/modules/multiversion
  - php -d sendmail_path=`which true` ~/drush.phar --root=$HOME/www --yes site-install --db-url=mysql://root:@127.0.0.1/drupal testing

script:
  - cd ~/www && php ./core/scripts/run-tests.sh --verbose --color --concurrency 4 --php `which php` --sqlite /tmp/test.sqlite --url http://localhost:8080 "multiversion" | tee /tmp/test.log ; export TEST_EXIT=${PIPESTATUS[0]}
  # Workaround so that we exit with the correct status.
  - TEST_LOG=$(! egrep -i "([0-9]+ fails)|(PHP Fatal error)|([0-9]+ exceptions)" /tmp/test.log > /dev/null)$?
  - if [ $TEST_EXIT -eq 0 ] && [ $TEST_LOG -eq 0 ]; then exit 0; else exit 1; fi
